apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"    
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: auctus/pedelogo-catalogo:v1.0.0
        ports:
          - containerPort: 80
        imagePullPolicy: Always
        resources: {}
        env:
          - name: Mongo__Host
            value: mongo-service
          - name: Mongo__DataBase
            value: admin
          - name: Mongo__Port
            value: "27017"       
          - name: Mongo__User
            value: mongouser
          - name: Mongo__Password
            value: mongopwd