apiVersion: v1
kind: ReplicationController
metadata:
  name: aplicacao-rc
  labels:
    project: xcalota
spec:
  replicas: 2
  template:
    metadata:
      name: nginx
      labels:
        project: xcalota
    spec:
      containers:
      - name: nginx-container
        image: nginx
