- hosts: webservers
  tasks:
    - name: Coleta o hostname
      command: hostname
    
    - name: Install apache2
      become: yes
      apt:
        name: ['apache2', 'php']
        state: present
        update_cache: yes    
    
    - name: enable service apache2 on boot
      become: yes
      systemd:
        name: apache2
        state: started
        masked: no
        enabled: yes

    - name: Copy website to apache folder
      become: yes
      copy:
        src: /home/ubuntu/playbooks/Website
        dest: /var/www/html/
        owner: root
        group: root
        mode: '0644'