---
- name: Resultado de um comando
  hosts: all
  tasks:
    - name: Execução de um comando
      ansible.builtin.shell: ps
      register: ps_result
    - name: Verificar o resultado
      ansible.builtin.debug:
        msg: "{{ ps_result.stdout  }}"
