apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-chiarellidev-cert
spec:
  secretName: chiarellidev-cert-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - "chiarellidev.com"