apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-homolog
  namespace: cert-manager
spec:
  acme:
    email: ca.chiarelli.97@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-homolog
    solvers:
    - http01:
        ingress:
          class: traefik
