apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:4.2.8
        ports:
          - containerPort: 27017
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.05"
          limits:
            memory: "4Gi"
            cpu: "2"         
        envFrom:
          - secretRef:
              name: mongodb-secret
