apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scw-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage-retain
