apiVersion: v1
kind: LimitRange
metadata:
  name: limite-container
spec:
  limits:
    - max:
        cpu: "800m"
        memory: "900Mi"
      min:
        cpu: "150m"
        memory: "99Mi"
      default:          # limits
        cpu: "250m"
        memory: "128Mi"    
      defaultRequest:   # requests
        cpu: "150m"
        memory: "100Mi"        
      type: Container # trabalhando de forma individual, olhando apenas para container