apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-configmap
data:
  Mongo__Host: {{ .Release.Name }}-mongo-service
  Mongo__DataBase: {{ .Values.mongodb.databaseName }}
  Mongo__Port: "27017"
