FROM python:3.9.16-slim-buster

LABEL MAINTAINER="Carlos Augusto Chiarelli <ca.chiarelli.97@gmail.com>"
LABEL APP_VERSION="1.0.0"

WORKDIR /app

COPY . . 

RUN pip install --no-cache-dir -r requirements.txt

RUN useradd carlos

USER carlos

EXPOSE 5000

CMD [ "python", "app.py"]
