FROM ubuntu

LABEL MAINTAINER="Carlos Augusto Chiarelli <ca.chiarelli.97@gmail.com>"
LABEL APP_VERSION="1.0.0"

ENV NPM_VERSION=8 ENVIRONMENT=PROD

RUN apt-get update && apt-get install -y git nano npm

WORKDIR /usr/share/myapp

RUN npm build

COPY requirements.txt requirements.txt

ADD ./file.tar.gz ./

RUN useradd carlos

USER carlos

EXPOSE 8080

VOLUME [ "/data" ]

ENTRYPOINT [ "ping" ]

CMD [ "localhost" ]
