version: '3.8'

networks:
  loki:
    driver: bridge

services:
  api:
    image: kubedevio/pedelogo-catalogo:v1.0.0
    ports:
      - 8080:80
    networks:
      - loki
    depends_on:
      - pedelogo-mongodb
    volumes:
      - "./logs/api:/log"
    environment:
      Mongo__Host: "pedelogo-mongodb"
      Mongo__User: "mongouser"
      Mongo__Password: "mongopwd"
      Mongo__Port: "27017"
      Mongo__Database: "admin"
  
  pedelogo-mongodb:
    image: mongo:4.1
    ports:
      - 27017:27017
    networks:
      - loki
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopwd
          
  loki:
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    networks:
      - loki
  
  promtail:
    image: grafana/promtail:2.0.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - "./promtail/config.yaml:/etc/promtail/config.yml"
      - "./logs/api:/logs/api"
      - "./tmp:/tmp"
    networks:
      - loki
    ports:
      - 9080:9080