apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - image: jaegertracing/all-in-one:1.28
          name: jaeger
          ports:
            - containerPort: 16686
            - containerPort: 14268

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
    - name: "16686"
      port: 16686
      targetPort: 16686
    - name: "14268"
      port: 14268
      targetPort: 14268
  selector:
    app: jaeger
  type: LoadBalancer
